### ISSUE TITLE
Header logo

### ISSUE THREAD

**Issue by orensomething1** [IronSummitMedia/startbootstrap-creative#19]
Hi, i love the Creative theme, one question please... about adding a logo: i added a png (transparent, 24bit) logo with white writing (in creative.css-> .navbar-default .navbar-header .navbar-brand) and managed to make it change to dark writing as the sticky menu enter (creative.css-> .navbar-default.affix .navbar-header .navbar-brand), 
but in mobile versions the background is white and then the default logo is not seen... (white on white). any solution for mobile version logo?
http://themarketplace.co.il/other/diamining/index.html#contact

Thank you very much!

**Comment by Palmer11** [comment]
Just override the image being changed:

```
.navbar-default .navbar-header .navbar-brand {
    background: url(http://webcream.co/logo-blk.png) no-repeat !important;
}

**Comment by orensomething1** [comment]
Hello Jordan,
but when doing so the main logo turns black...
i am using two logos, since the sticky menu's background (in desktop view)
turns white when scrolling and the menu items + logo needs to be dark.
 i would like to have the desktop view settings to preserve in mobile view.

you can see it for youself in this sample:
http://themarketplace.co.il/other/diamining/index.html drag the window to
bring the mobile view.

Thank you...
Oren

**Comment by Palmer11** [comment]
I am not sure where you are getting this black logo from. I understand what you mean with the background changing. You can add a media query to fix this:

```
@media (max-width: 768px) {
    .navbar-default .navbar-header .navbar-brand {
        background: url(http://webcream.co/logo-blk.png) no-repeat !important;
    }
}
```

For more information on the bootstrap media queries, you can view it here:
http://getbootstrap.com/css/#grid-media-queries

**Comment by orensomething1** [comment]
it works!
thank you so much... if you dont mind ill upload it to the theme's page so
will be available for others...

Have a great day!

**Comment by Palmer11** [comment]
Sounds great. Remember to close your ticket if the issue has been resolved.
