### ISSUE TITLE
not responsive

### ISSUE THREAD

**Issue by suyogchoudhari** [IronSummitMedia/startbootstrap-creative#3]
I download code from github, UI looks good but its not responsive. Do I need to do anything extra?

**Comment by suyogchoudhari** [comment]
it works when I add it to web / app server..

**Comment by suyogchoudhari** [comment]
looks like there is bug with FF 36.0.3 version. Its working on chrome.

**Comment by davidtmiller** [comment]
The responsive issues should be fixed with this next release.
